fix: scroll-options stops using is3dSupported
RaspberryPiFoundation/blockly-samples pull request #1363
Opened 2022-11-04 22:23 UTC by HollowMan6

This is a follow up on:
- #1202
- https://github.com/google/blockly/pull/6400
- https://github.com/mit-cml/workspace-multiselect/pull/6

As `is3dSupported` has been removed in Blockly 9, the [workspace-multiselect](https://github.com/mit-cml/workspace-multiselect) plugin v0.1.3 will choose to use "`Blockly.WorkspaceSvg.getBlockDragSurface` always return `false`" to disable dragsurface, which means now it's OK to remove `is3dSupported` here in scroll-options.

Signed-off-by: Hollow Man <hollowman@opensuse.org>

2022-11-10 19:24 UTC, rachel-fenichel requested changes

2022-11-10 19:24 UTC, rachel-fenichel commented on plugins/scroll-options/src/utils.js
> +  const translation = ws.svgBlockCanvas_.getAttribute('transform');
How about moving the check for `dragSurface` into this function and having it automatically return either `dragSurface.getWsTranslation` or the rest of this function? That lets you avoid duplicating code in the three places where this is called.

2022-11-10 19:24 UTC, rachel-fenichel commented on plugins/scroll-options/src/utils.js
> + * Copyright 2021 Google LLC
2022

2022-11-10 23:59 UTC, HollowMan6 commented
Fixed, thanks for reviewing!

2022-11-11 00:01 UTC, rachel-fenichel approved these changes

2022-11-11 00:03 UTC, merged