feat: time picker field WIP
RaspberryPiFoundation/blockly-samples pull request #1385
Opened 2022-11-21 01:12 UTC by JankyCS

![image](https://user-images.githubusercontent.com/42399554/202937769-713acc57-1d23-48c8-85ef-907798f879dd.png)

https://github.com/google/blockly-samples/issues/522

This field is implemented differently from some of the other field plugins because it does not use the `DropDownDiv` for it's time picker popup. This is because it uses [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time](HTML time input). as per https://github.com/google/blockly-samples/issues/522#issuecomment-1259830986, and the time picker popup can not be placed into the dropdown div(as far as I can tell). 

Instead, `widgetCreate_` is overridden to produce an invisible HTML time input.

2022-11-21 17:02 UTC, BeksOmega commented
Woo that looks sweet! I think you should be able to put in the dropdowndiv though, because the dropdowndiv is just a fancy div. Could you explain a bit more about what issues you ran into?

2022-11-21 17:37 UTC, JankyCS commented
![image](https://user-images.githubusercontent.com/42399554/203122424-9633634f-2b49-456e-9fb3-c4c8634e50f2.png)
 The actual time picker is what appears when you click the clock on the right side of a `<input type='time'/>` and I programmatically force it to appear using a call to `showPicker()`. I don't think this popup is an HTML element that can be placed inside of a div.

2022-12-02 19:56 UTC, cpcallen requested changes
There's a bunch of (mostly trivial) comments about the code below.  Overall, my thoughts are:

* This is great and looks great!
* Unfortunately, it does not actually work.  🙁

I suspect it's a locale issue (I'm in the UK and have 24h time turned on).  The picker looks like this:
<img width="179" alt="Screenshot 2022-12-02 at 19 49 36" src="https://user-images.githubusercontent.com/5603958/205374560-cdb93bd9-9a8e-4192-bf27-63b55a13d6c1.png">
and I can pick times no problem, but any time I pick a (and thereby change the time) I get the following error in the console:
```
field_textinput.ts?dc62:512 The specified value "undefined" does not conform to the required format.  The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.
setEditorValue_	@	field_textinput.ts?dc62:512
eval	@	field_time.js?6b7f:79
onClick_	@	unknown
```
and the time field is left blank.

I'm on macOS Monterey 12.6.1, using Chrome 107.0.5304.121, with my system local settings as follows:
- Region: United Kingdom (Custom)
- Calendar: Gregorian
- Time Format: 24h time


Additionally: although popping up the picker should clearly be the default method of entry when one clicks on the field, it would be nice if there were also a way to edit the time using the keyboard.  (Maybe this is possible if one does not encounter the above error?)


Overall very promising.

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/GETSTARTED.md
> +This package was bootstrapped with [@blockly/create-package](https://www.npmjs.com/package/@blockly/create-package).
N.B.: I've queried with my colleagues about whether we actually want this file committed or not.  Leave it for now, but we might delete it (and its many sibling `plugins/field-*/GETSTARTED.md` files).

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/README.md
> +A [Blockly](https://www.npmjs.com/package/blockly) plugin that ...
Obviously this (and the Usage and API sections below) will need to be written.

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/src/index.js
> +export * from './field_time';
This file is a little useless.  I'd suggest getting rid of it and just adjusting the package's entry point, but evidently the `build` script depends on it existing—so why not replace it with the contents of `field_time.js` (which can then be deleted)?

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/src/field_time.js
> + * Copyright 2020 Google LLC
```suggestion
 * Copyright 2022 Google LLC
```

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/package.json
> +  "description": "A Blockly plugin.",
This will need to be written.

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/package.json
> +  "name": "blockly-plugin-field-time",
```suggestion
  "name": "@blockly/field-time",
```

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/package.json
> +  "version": "0.0.0",
This will need to be set to `1.0.0` before this PR is merged.

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/package.json
> +  },
These will need to be updated as well:
```suggestion
  "homepage": "https://github.com/google/blockly-samples/tree/master/field-time#readme",
  "bugs": {
    "url": "https://github.com/google/blockly-samples/issues"
  },
```

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/package.json
> +    "directory": "plugins\\field-time"
```suggestion
    "url": "https://github.com/google/blockly-samples.git",
    "directory": "plugins/field-time"
```

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/package.json
> +  "publishConfig": {},
```suggestion
  "publishConfig": {
    "access": "public",
    "registry": "https://wombat-dressing-room.appspot.com"
  },
```
(Don't ask.)

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/GETSTARTED.md
> +This package was bootstrapped with [@blockly/create-package](https://www.npmjs.com/package/@blockly/create-package).
Update: this file should be deleted (once you are familiar with its contents).

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/src/field_time.js
> +   *    'HH:MM' format. Defaults to 12:00.
Probably worth clarifying that this will be in 24h format.

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/src/field_time.js
> +      /^([0-1]?[0-9]|2[0-4]):([0-5][0-9])(:[0-5][0-9])?$/.test(newValue);
* Do you want to accept `24:00`?  Do you want to accept `24:59`?
* Do you want to accept seconds?  The description suggests it's strictly HH:MM.
* The middle set of parens appear to be superfluous:
  ```suggestion
        /^([0-1]?[0-9]|2[0-4]):[0-5][0-9](:[0-5][0-9])?$/.test(newValue);
  ```
* An alternative approach might be to match against `/^(\d\d?):(\d\d)(?::(\d\d))?$/` and then check the submatches numerically.  (Probably not simpler, but worth keeping in mind if the regexp starts getting out of hand.)

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/src/field_time.js
> +    }
I might try:
```JS
  if (!/…detail omitted…/.test(newValue) {
    return null;
  }
```
(If it fits in 80 columns!)

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/src/field_time.js
> +  widgetCreate_() {
Does this need to be marked `protected`?  I'm slightly unclear: I know `public` is the default, and that `protected` method can be overridden to make it `public`, but not sure if that happens in the absence of a visibility modifier.

(Same for `showEditor_` below.)

2022-12-02 19:56 UTC, cpcallen commented on plugins/field-time/src/field_time.js
> +    }
Do you intend to show both an editor pop-up and the picker?  Testing on macOS I see only the picker.

2022-12-02 22:48 UTC, JankyCS commented on plugins/field-time/src/index.js
> +export * from './field_time';
Will do. I actually copied this from the `field_slider` plugin so it should probably be refactored there as well?

2022-12-02 22:56 UTC, JankyCS commented on plugins/field-time/src/field_time.js
> +    }
The editor has the picker within it (its opacity is 0 so you can't see it), and we call `showPicker` in `showEditor_` just to trigger the picker to appear.

2022-12-02 23:07 UTC, JankyCS commented
> Additionally: although popping up the picker should clearly be the default method of entry when one clicks on the field, it would be nice if there were also a way to edit the time using the keyboard. (Maybe this is possible if one does not encounter the above error?)

I tried to allow the user to edit the time using the keyboard but ultimately decided against it. The reason is that when the `<input type=time/>` popup appears, it prevents any keyboard strokes from being read. I always want this popup to appear on click, so then the user would have to click again in the text area to make the popup disappear in order to actually start typing input. This behavior felt unintuitive to me.

It also comes with the side-effect that the user would be unable to reopen the popup once they start typing input (right now additional clicks just close and re-open the popup, but I would have to disable this behavior). The user would need to deselect the block and then click the area again to get the popup, which also isn't desirable.

I don't think a text input is very important for a time picker. For example, the date picker needs text input because its popup only allows traversing by one month at a time, so it can take a very long time to get to a desired date. The time-picker does not have this issue, since it is limited by the 24-hour clock and it is quick to get any desired time.

Happy to discuss more about this.

2022-12-03 00:28 UTC, JankyCS commented on plugins/field-time/src/index.js
> +    super(initial, validator);
Originally I just called `super('12:00', validator)` followed by `this.setValue(value)`, which seemed to work fine. However, the mocha test wouldn't let me do this (can't call setValue in the constructor?) so I factored out the validator.

Mocha error:
![image](https://user-images.githubusercontent.com/42399554/205412781-b6e16e4e-4e92-4141-8339-48b2028fdd7b.png)

2022-12-16 03:10 UTC, JankyCS commented
@cpcallen

2023-02-13 17:48 UTC, BeksOmega commented
I'm going to go ahead and close this becausae we're not planning to merge as is, but we can always reopen if necessary =)

2023-02-13 18:27 UTC, BeksOmega commented
Reopening per christopher's request.

2023-05-22 15:08 UTC, BeksOmega commented
I'm closing this again since it's been 3 months.

2023-05-22 15:08 UTC, closed without merging