chore: xml to json dev-tools question
RaspberryPiFoundation/blockly-samples pull request #1411
Opened 2022-12-07 21:45 UTC by mikebarr24

struggling a little with this. I can't get a math_number attached at 142. Wondering if you could take a look.

2022-12-14 21:29 UTC, BeksOmega commented on plugins/dev-tools/src/toolboxCategories.js
> +            //unsure what goes here.
Here's the JSON generated using the [playground](https://blockly-demo.appspot.com/static/tests/playground.html)!

```
{
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "math_single",
        "id": "7P#.3msd$=xW5`G9UN2q",
        "x": 212,
        "y": 212,
        "fields": {
          "OP": "ROOT"
        },
        "inputs": {
          "NUM": {
            "shadow": {
              "type": "math_number",
              "id": "MEt,JJH^y`bZ#2{9C$L}",
              "fields": {
                "NUM": 9
              }
            }
          }
        }
      }
    ]
  }
}
```

You def want to clean it up a bit (e.g. removing IDs) but hopefully that shows you how it works =)

Best wishes! --Beka

2023-01-02 11:14 UTC, mikebarr24 commented
I'm struggling to use the output from playground which is why I had initially just been changing line by line. 

I've just added the first toolbox to the most recent commit here and this is the output I'm getting in the console.
```
toolbox.ts?af41:327 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at eval (toolbox.ts?af41:327:29)
    at Array.filter (<anonymous>)
    at isCategoryCollapsible$$module$build$src$core$utils$toolbox (toolbox.ts?af41:325:56)
    at Toolbox$$module$build$src$core$toolbox$toolbox.createToolboxItem_ (toolbox.ts?a4a2:400:17)
    at Toolbox$$module$build$src$core$toolbox$toolbox.renderContents_ (toolbox.ts?a4a2:381:12)
    at Toolbox$$module$build$src$core$toolbox$toolbox.render (toolbox.ts?a4a2:364:10)
    at Toolbox$$module$build$src$core$toolbox$toolbox.init (toolbox.ts?a4a2:155:10)
    at init$$module$build$src$core$inject (inject.ts?29a4:243:15)
    at Object.inject$$module$build$src$core$inject [as inject] (inject.ts?29a4:81:3)
    at createWorkspace (index.js?0441:22:21)
```

I've looked through the documentation and can't find how to format the output of playground into json. 

Copy and pasting everything between the xml tags doesn't work.

2023-01-03 17:03 UTC, BeksOmega commented
Hello! It looks like the `"contents"` property of your category is structured slightly incorrectly. Instead of having a `"blocks"` property, the `"contents"` property is an array where each element has a `"type"` property (usually specifying that it is a block).

Here's an example from the [documentation](https://developers.google.com/blockly/guides/configure/web/toolbox#categories):
```
{
  "kind": "categoryToolbox",
  "contents": [
    {
      "kind": "category",
      "name": "Control",
      "contents": [
        {
          "kind": "block",
          "type": "controls_if"
        },
      ]
    },
    {
      "kind": "category",
      "name": "Logic",
      "contents": [
        {
          "kind": "block",
          "type": "logic_compare"
        },
        {
          "kind": "block",
          "type": "logic_operation"
        },
        {
          "kind": "block",
          "type": "logic_boolean"
        }
      ]
    }
  ]
}
```

2023-01-03 21:00 UTC, mikebarr24 commented
Hey @BeksOmega 
Let me know if this looks OK :)

2023-01-05 16:13 UTC, BeksOmega requested changes
Lookin much better! Thank you for going back and forth with me on this =) And thank you for all of your hard work!

2023-01-05 16:13 UTC, BeksOmega commented on plugins/dev-tools/src/toolboxSimple.js
> +/* `<xml xmlns="https://developers.google.com/blockly/xml" id="toolbox-simple" style="display: none">
Please remove the commented out code here =)

2023-01-05 16:13 UTC, BeksOmega commented on plugins/dev-tools/src/toolboxCategories.js
> +                'id': 'Y.z2N%rZVW2$WG~Rr3jV',
Remove ID.

2023-01-05 16:13 UTC, BeksOmega commented on plugins/dev-tools/src/toolboxCategories.js
> +                'id': 'o(J=1}3OGC}o{WXU^~O?',
Remove ID.

2023-01-05 16:13 UTC, BeksOmega commented on plugins/dev-tools/src/toolboxCategories.js
> +          'extraState': '<mutation divisor_input=\'false\'></mutation>',
You should be able to remove any `extraState` properties that have XML in them. Here and below.

2023-01-05 16:13 UTC, BeksOmega commented on plugins/dev-tools/src/toolboxSimple.js
> +    'blocks': [
This needs to be refactored to have the toolbox format, rather than the serialization format.

2023-01-05 16:13 UTC, BeksOmega commented on plugins/dev-tools/src/toolboxSimple.js
> +  ],
This property can be removed because it isn't compatible with the toolbox format.

2023-01-05 16:13 UTC, BeksOmega commented on plugins/dev-tools/src/toolboxSimple.js
> +                },
This should be replaced with the full variable state. (name and type)

2023-01-05 19:39 UTC, mikebarr24 commented
@BeksOmegaNo problem! I'm enjoying it!😀 

OK I think I've changed those things. Let me know if anything else needs done.

2023-01-05 21:15 UTC, BeksOmega approved these changes
LGTM! Can you just confirm that you tested this running `npm run start` in the dev-tools directory, and checking that both toolboxes looked correct? Then I should be able to get this merged!

2023-01-05 21:55 UTC, mikebarr24 commented
There is something a bit funny going on switching between toolboxes. 
It doesn't seem to want to revert to categories. There are no obvious errors in the console. 

https://user-images.githubusercontent.com/89523154/210887426-0077a3e1-b3c9-48cf-be62-c1269b3c14b2.mov

2023-01-08 22:08 UTC, mikebarr24 commented
Think I figured out where it's going wrong. Ran out of time tonight but hopefully will get it sorted tomorrow.

2023-01-09 21:48 UTC, BeksOmega commented
@mikebarr24 Did the last commit include all of the files you wanted it to? I don't see what changed wrt the logic.

2023-01-19 16:49 UTC, BeksOmega commented
@mikebarr24 Just wanted to bump this incase you didn't get notified about my previous message!

2023-01-20 19:24 UTC, mikebarr24 commented
Hey @BeksOmega Yes! Sorry. Still looking at this. Been busy at work. There is something not working in 

dev-tools>>src>>playground>>options.js 

that I can't figure out.

2023-01-23 22:49 UTC, mikebarr24 commented
Hey @BeksOmega Ok. Think this should be it. Everything is working as it should.

2023-01-24 21:26 UTC, BeksOmega commented
Sweetness, thank you for your work on this @mikebarr24 !

2023-01-24 21:27 UTC, merged