feat: Revise fields
RaspberryPiFoundation/blockly-samples pull request #1700
Opened 2023-05-18 15:39 UTC by NeilFraser

2023-05-18 16:40 UTC, BeksOmega approved these changes

2023-05-23 12:56 UTC, NeilFraser commented
Ok, this is ready now.
Honestly, I can't read the math in this PR.  It's write-only code.

2023-05-23 16:31 UTC, BeksOmega requested changes
Only one actual change required! (The one related to `doClassValidation_`). Otherwise just questions =)

2023-05-23 16:31 UTC, BeksOmega commented on plugins/field-angle/src/field_angle.ts
> +    if (config.symbol !== undefined) this.symbol = config.symbol;
This is configurable now to support radians?

2023-05-23 16:31 UTC, BeksOmega commented on plugins/field-angle/src/field_angle.ts
> +    if (minorTickAngle) {
Is this to support disabling the ticks if someone sets the `minorTick` to 0?

2023-05-23 16:31 UTC, BeksOmega commented on plugins/field-angle/src/field_angle.ts
> +    const validAngle = this.doClassValidation_(angle);
I don't think we want to pass the new value through class validation before setting the editor value. This would mean that if a user entered a value outside the valid min/max, we would update the text input to show something they didn't type (which we generally do not do).

`setEditorValue_` will pass the angle to `setValue` which will pass it through `doClassValidation_`. So the value of the angle field will always be valid anyway.

2023-05-23 16:31 UTC, BeksOmega commented on plugins/field-angle/src/field_angle.ts
> +  symbol: string;
Symbol should be `?:` as well.

2023-05-23 16:31 UTC, BeksOmega commented on plugins/field-angle/test/index.ts
> +  },
Yay thank you for adding test blocks :D

2023-05-23 16:31 UTC, BeksOmega commented on plugins/field-angle/src/field_angle.ts
> +  private fieldAngleToRadians(angle: number): number {
Love separating this out into a helper method - much cleaner =)

2023-05-23 17:20 UTC, NeilFraser commented on plugins/field-angle/src/field_angle.ts
> +    if (config.symbol !== undefined) this.symbol = config.symbol;
Correct.  Now that 360 isn't hardcoded into the field, we now have to consider radians, turns, gons, zams, etc.

2023-05-23 17:20 UTC, NeilFraser commented on plugins/field-angle/src/field_angle.ts
> +    if (minorTickAngle) {
Correct.  As it says in the comment: Zero to disable.

2023-05-23 17:20 UTC, NeilFraser commented on plugins/field-angle/src/field_angle.ts
> +  private fieldAngleToRadians(angle: number): number {
The overall math remains incomprehensible IMHO.

2023-05-23 17:20 UTC, NeilFraser commented on plugins/field-angle/src/field_angle.ts
> +  symbol: string;
Right.

2023-05-23 18:11 UTC, BeksOmega approved these changes

2023-05-23 18:13 UTC, BeksOmega commented on plugins/field-angle/src/field_angle.ts
> +    const validAngle = this.doClassValidation_(angle);
We tested it, and for some reason this is necessary, but we're not sure why. Not worth digging into at the moment.

2023-05-23 18:13 UTC, merged