fix: support xml serialized blocks in setContents() of workspace-back…
RaspberryPiFoundation/blockly-samples pull request #1835
Opened 2023-07-31 05:25 UTC by johnnyoshika

Add support for loading serialized XML contents into Backpack for backwards compatibility.

Note: XML support is only during Backpack hydration through backpack.setContents(). Getting contents of the Backpack through backpack.getContents() will still return JSON.

Question to the Blockly team: I assumed in this PR that all Backpack serialized XML starts with `<block`. Please let me know if this was an incorrect assumption and I'll make the necessary changes.

2023-07-31 18:39 UTC, rachel-fenichel commented
Swapping review to Beka for serialization.

2023-07-31 23:11 UTC, BeksOmega requested changes
This LGTM! Normally I would ask for unit tests but since this plugin isn't set up for that atm I'm not gonna ask you to do that :P

Could you write a comment explaining how you manually tested + verified this so we know that it's working?

2023-07-31 23:11 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.js
> +    if (!blockXml.startsWith('<block')) {
This assumption should be fine!

2023-07-31 23:11 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.js
> +   * @param {!string} blockXml The XML serialized block.
```suggestion
   * @param {string} blockXml The XML serialized block.
```

Primitives are non-null by default =)

2023-07-31 23:11 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.js
> +    const workspace = new Blockly.Workspace();
Can you call `.dispose` on this at the end of the method to make sure we're not leaking any state? E.g. workspaces get registered so they can be retrieved with `Blockly.getWorkspaceById`, and disposing removes that registration.

2023-08-02 06:25 UTC, johnnyoshika commented
> This LGTM! Normally I would ask for unit tests but since this plugin isn't set up for that atm I'm not gonna ask you to do that :P
> 
> Could you write a comment explaining how you manually tested + verified this so we know that it's working?

I updated the PR description with a section on `Tests`. I've also resolved your other change requests. Thanks for the review!

2023-08-02 15:25 UTC, BeksOmega approved these changes
Thanks for the fixes :D This should go out with the Thursday release!

2023-08-02 15:25 UTC, merged

2023-08-04 17:29 UTC, gonfunko commented
@johnnyoshika Thanks for this! I think we're good to close #1827, or was there something else you planned to address?

2023-08-14 02:23 UTC, johnnyoshika commented
@gonfunko Yes, https://github.com/google/blockly-samples/issues/1827 can now be closed.