fix: minimap rendering issue
RaspberryPiFoundation/blockly-samples pull request #1931
Opened 2023-09-14 02:03 UTC by itsfloki

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details
### Resolves

Fixes Issue #1926

### Proposed Changes

This PR modify the [minimap inject call](https://github.com/google/blockly-samples/blob/e45ad05b9f5f6cb717b8337c60df09fa0128e06b/plugins/workspace-minimap/src/minimap.ts#L64) to copy the renderer from the `primaryWorkspace`

### Reason for Changes

As discussed in the issue, if we change the renderer option from `geras` to `zelos` in the main workspace then the minimap still uses the `geras` renderer. So if we use the renderer of the main workspace in minimap then this issue will be resolved.

### Test Coverage

1. Run it using the steps mentioned in the issue.

2023-09-14 16:27 UTC, BeksOmega requested changes
This LGTM! Just one lint fix =)

2023-09-14 16:27 UTC, BeksOmega commented on plugins/workspace-minimap/src/minimap.ts
> +            renderer: this.primaryWorkspace.options.renderer
```suggestion
            renderer: this.primaryWorkspace.options.renderer,
```

2023-09-16 00:47 UTC, itsfloki commented
@BeksOmega I have fixed the lint.

2023-09-18 13:03 UTC, BeksOmega commented
Sweet! Thank you for your contribution @itsfloki  :D This looks great! Let me know if you'd like to work on another issue and I can recommend some for you =)

2023-09-18 13:03 UTC, merged

2023-09-18 13:17 UTC, itsfloki commented
> Sweet! Thank you for your contribution @itsfloki :D This looks great! Let me know if you'd like to work on another issue and I can recommend some for you =)

Yaa sure

2023-09-18 14:31 UTC, BeksOmega commented
@itsfloki would you be interested in https://github.com/google/blockly-samples/issues/1922 ? If so could you comment there so I can assign you?

Best wishes,
--Beka