fix: Update to use JSON tool definitions
RaspberryPiFoundation/blockly-samples pull request #1968
Opened 2023-09-22 22:20 UTC by karenjohn35

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details
### Resolves

Fixes 
#1263 

### Proposed Changes

### Reason for Changes

### Test Coverage

### Documentation

### Additional Information

2023-09-24 12:39 UTC, BeksOmega requested changes
This looks great! Just two little fixes then should be good to go =)

Thank you for your hard work on this!

2023-09-24 12:39 UTC, BeksOmega commented on examples/rtl-demo/index.html
> +      var toolbox = {
```suggestion
      const toolbox = {
```

2023-09-24 12:39 UTC, BeksOmega commented on examples/rtl-demo/index.html
> +      var workspace = Blockly.inject('blocklyDiv',
```suggestion
      const workspace = Blockly.inject('blocklyDiv', 
```

2023-09-25 21:23 UTC, debaraj-barua commented on examples/rtl-demo/index.html
Perhaps L390-L515 can be removed?

https://github.com/google/blockly-samples/blob/772b45371cd1fa02d9feeade8be28ddce318dd32/examples/rtl-demo/index.html#L390-L515

2023-09-26 15:52 UTC, BeksOmega commented on examples/rtl-demo/index.html
That would be great as well =) Thanks for the catch @debaraj-barua !

2023-10-02 16:30 UTC, BeksOmega commented
Heya @karenjohn35  Just wanted to check that you're still interested in working on this! Otherwise I'm going to close it on Friday 2023/10/06 so we don't have stale PRs =) Thank you again for your work on this!

2023-10-04 17:37 UTC, karenjohn35 commented on examples/rtl-demo/index.html
How can I accept these changes?

2023-10-04 17:38 UTC, karenjohn35 commented
Hi @BeksOmega! I think you can resolve this pull request after I implement the changes @debaraj-barua proposed. I am not entirely sure how I can do that. Would I have to create another pull request?

2023-10-06 19:05 UTC, BeksOmega commented
You would need to:

1) Check out your OSD branch. `git switch osd`
2) Delete the lines debaraj suggested
3) Commit the changes. `git commit -am "fix: delete xml"`
4) Push the changes to your remote. `git push origin osd`

Then I can get this merged!

2023-10-06 19:05 UTC, BeksOmega commented on examples/rtl-demo/index.html
The UI here is a bit confusing, this isn't a suggested edit, just a link to the relevant lines of code!

2023-10-06 19:34 UTC, karenjohn35 commented
Thanks, I just made that edit!

2023-10-06 21:08 UTC, BeksOmega approved these changes

2023-10-06 21:09 UTC, merged

2023-10-06 21:09 UTC, BeksOmega commented
Thank you so much for the work on this @karenjohn35 This looks great :D