Add indexing of dropdown entries
RaspberryPiFoundation/blockly-samples pull request #2004
Opened 2023-10-04 12:47 UTC by koenvanwijk

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details
### Resolves

[Fixes ](https://github.com/google/blockly-samples/issues/2003)

### Proposed Changes
The search should find the block and select the dropdown item. 
![image](https://github.com/google/blockly-samples/assets/8227977/83be860a-40df-47cc-9c8e-bb7125c26e67)

### Reason for Changes
The search fails to find blocks with dropdown.

### Test Coverage
The manual test show the blocks are found and that the option is selected. 

### Documentation
No update of the documentation is required. Although an remark could be made.

### Additional Information

2023-10-04 15:38 UTC, BeksOmega commented
We have a partial fix for this on the OSD branch: https://github.com/google/blockly-samples/pull/1971

It adds the indexing but doesn't fix the blocks. We're planning to merge that early next week (we're doing a design sprint this week) so I'll come back to this after that is done so we can get it rebased and integrated!

2023-10-06 04:53 UTC, ludizhan commented
FYI I got assigned to the original issue https://github.com/google/blockly-samples/issues/1940 and was looking into the part 2 of fix. I was looking into how to represent blocks in json and was about to raise questions around this.
If you would like to take over the issue, maybe comment on the original issue first would be better so that we don't do the duplicate work.

2023-10-06 06:49 UTC, koenvanwijk commented
@ludizhan  Please have a look at the implementation of the toolbox where the option of a dropdown is set, I am fine if you take it in the delivery of #1940.

2023-10-07 01:23 UTC, ludizhan commented
Thanks, created https://github.com/google/blockly-samples/pull/2013 for the osd branch.

2023-11-27 21:58 UTC, BeksOmega commented
We ended up having to close the other PR, so circling back on this! I gave it a test and there are a few issues, but generally looks good.

Are you still interested in working on this @koenvanwijk ?

2023-11-28 12:14 UTC, koenvanwijk commented
Yes, I assumed the other solution would be integrated... consequently, I waited. What are the issues?

Regards,
Koen

________________________________
From: Beka Westberg ***@***.***>
Sent: Monday, November 27, 2023 22:58
To: google/blockly-samples ***@***.***>
Cc: Koen van Wijk ***@***.***>; Mention ***@***.***>
Subject: Re: [google/blockly-samples] Add indexing of dropdown entries (PR #2004)


We ended up having to close the other PR, so circling back on this! I gave it a test and there are a few issues, but generally looks good.

Are you still interested in working on this @koenvanwijk<https://github.com/koenvanwijk> ?

—
Reply to this email directly, view it on GitHub<https://github.com/google/blockly-samples/pull/2004#issuecomment-1828687880>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AB6YZCOJLQ3PHJXHPCXQ4ITYGUEIVAVCNFSM6AAAAAA5SSH6G6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRYGY4DOOBYGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



-------- Disclaimer --------
This email and any files transmitted may contain proprietary and confidential information of ICT Group or any of its subsidiaries (“ICT”) and is intended only for the (use of the) named recipient(s) above. If you have received this message in error or are not the intended or named recipient(s) of this message, please immediately notify the sender by return and delete this email message from your computer. Any views or opinions presented are solely those of its author and do not necessarily represent those of ICT. You are hereby notified that unauthorized disclosure, use, dissemination, forwarding, printing or copying of this e-mail and its attachments either whole or partial of its contents is strictly prohibited. ICT cannot guarantee that email communications are secured and error-free and does not accept any liability for damages resulting from the use of email. The general terms and conditions of purchase respectively sale and delivery of ICT are applicable to all transactions and undertakings resulting therefrom.

2023-11-28 19:28 UTC, BeksOmega requested changes
Thanks for still be interested in this! Appreciate your patience =)

I saw an issue yesterday where searching for variable names would create new variables in the workspace. But I'm not sure if that's actually an issue or if I just rebased your code incorrectly.

Could you rebase this and then make the changes requested? Then I'll give this another manual test!

2023-11-28 19:28 UTC, BeksOmega commented on plugins/toolbox-search/src/block_searcher.ts
Changes to this file are unnecessary because the other PR added indexing.

2023-11-28 19:28 UTC, BeksOmega commented on plugins/toolbox-search/src/toolbox_search.ts
> +              // check the block if it has dropdowns
Can you remove the inline comments throughout? I think the code is self-explanatory!

2023-11-28 20:25 UTC, koenvanwijk commented
Yes indeed the code is readable. But I wrote the comments not the code 😉. I agree the comment can be removed now.

Is creating a new variable a side effect of const block = this.workspace_.newBlock(blockType); ?



________________________________
From: Beka Westberg ***@***.***>
Sent: Tuesday, November 28, 2023 20:28
To: google/blockly-samples ***@***.***>
Cc: Koen van Wijk ***@***.***>; Mention ***@***.***>
Subject: Re: [google/blockly-samples] Add indexing of dropdown entries (PR #2004)


@BeksOmega requested changes on this pull request.

Thanks for still be interested in this! Appreciate your patience =)

I saw an issue yesterday where searching for variable names would create new variables in the workspace. But I'm not sure if that's actually an issue or if I just rebased your code incorrectly.

Could you rebase this and then make the changes requested? Then I'll give this another manual test!

________________________________

On plugins/toolbox-search/src/block_searcher.ts<https://github.com/google/blockly-samples/pull/2004#discussion_r1408283851>:

Changes to this file are unnecessary because the other PR added indexing.

________________________________

In plugins/toolbox-search/src/toolbox_search.ts<https://github.com/google/blockly-samples/pull/2004#discussion_r1408284354>:

> @@ -161,9 +161,45 @@ export class ToolboxSearchCategory extends Blockly.ToolboxCategory {
     this.flyoutItems_ = query ?
         this.blockSearcher.blockTypesMatching(query).map(
             (blockType) => {
+              // check the block if it has dropdowns


Can you remove the inline comments throughout? I think the code is self-explanatory!

—
Reply to this email directly, view it on GitHub<https://github.com/google/blockly-samples/pull/2004#pullrequestreview-1753723956>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AB6YZCOLXTW5ETMWJNFPLUDYGY3M5AVCNFSM6AAAAAA5SSH6G6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONJTG4ZDGOJVGY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



-------- Disclaimer --------
This email and any files transmitted may contain proprietary and confidential information of ICT Group or any of its subsidiaries (“ICT”) and is intended only for the (use of the) named recipient(s) above. If you have received this message in error or are not the intended or named recipient(s) of this message, please immediately notify the sender by return and delete this email message from your computer. Any views or opinions presented are solely those of its author and do not necessarily represent those of ICT. You are hereby notified that unauthorized disclosure, use, dissemination, forwarding, printing or copying of this e-mail and its attachments either whole or partial of its contents is strictly prohibited. ICT cannot guarantee that email communications are secured and error-free and does not accept any liability for damages resulting from the use of email. The general terms and conditions of purchase respectively sale and delivery of ICT are applicable to all transactions and undertakings resulting therefrom.

2023-11-29 16:47 UTC, BeksOmega commented
Hm ok so I looked at this again, and I think we should actually reorganize this a bit. I think the BlockSearcher should handle saving the field values in the trigrams map, instead of re-searching for the dropdown fields in the ToolboxSearchCategory. That way we can also easily match the alt text (which is currently being indexed, but not selected when searching), and it's more performant. 

So the trigrams map will change to be:
```
private trigramsToBlocks = new Map<string, Set<Blockly.serialization.blocks.State>>();
```

And `indexDropdownOption` will save the field value as part of the `State`.

2023-12-19 18:47 UTC, savakarrohan commented
As an end user of the `toolbox-search` package, I've noticed that it doesn't support multiple workspaces. 
Any tips? Should I submit an issue?

```
console.js:213  Error: Shortcut named "startSearch" already exists.
    at ShortcutRegistry$$module$build$src$core$shortcut_registry.register (shortcut_registry.ts:55:17)
    at r.registerShortcut (toolbox_search.ts:95:5)
    at new r (toolbox_search.ts:42:10)
    at Toolbox$$module$build$src$core$toolbox$toolbox.createToolboxItem_ (toolbox.ts:426:27)
    at Toolbox$$module$build$src$core$toolbox$toolbox.renderContents_ (toolbox.ts:394:12)
    at Toolbox$$module$build$src$core$toolbox$toolbox.render (toolbox.ts:377:10)
    at Toolbox$$module$build$src$core$toolbox$toolbox.init (toolbox.ts:150:10)
    at init$$module$build$src$core$inject (inject.ts:239:15)
    at Object.inject$$module$build$src$core$inject [as inject] (inject.ts:65:3)
    at BlocklyLayout.onAfterAttach (layout.ts:62:23)
```

2023-12-19 19:45 UTC, BeksOmega commented
> As an end user of the `toolbox-search` package, I've noticed that it doesn't support multiple workspaces. Any tips? Should I submit an issue? Could you direct me to which part of code too? Would love to open up a pull request too!
> 
> ```
> console.js:213  Error: Shortcut named "startSearch" already exists.
>     at ShortcutRegistry$$module$build$src$core$shortcut_registry.register (shortcut_registry.ts:55:17)
>     at r.registerShortcut (toolbox_search.ts:95:5)
>     at new r (toolbox_search.ts:42:10)
>     at Toolbox$$module$build$src$core$toolbox$toolbox.createToolboxItem_ (toolbox.ts:426:27)
>     at Toolbox$$module$build$src$core$toolbox$toolbox.renderContents_ (toolbox.ts:394:12)
>     at Toolbox$$module$build$src$core$toolbox$toolbox.render (toolbox.ts:377:10)
>     at Toolbox$$module$build$src$core$toolbox$toolbox.init (toolbox.ts:150:10)
>     at init$$module$build$src$core$inject (inject.ts:239:15)
>     at Object.inject$$module$build$src$core$inject [as inject] (inject.ts:65:3)
>     at BlocklyLayout.onAfterAttach (layout.ts:62:23)
> ```

Yes please open an issue for this with reproduction steps!

2024-01-05 16:31 UTC, BeksOmega commented
Heya @koenvanwijk are you still interested in working on this? I'll check back in a week and close it if not!

2024-01-05 18:53 UTC, koenvanwijk commented
I found a colleague that works on it. Expect a pull request next week.

2024-01-08 07:58 UTC, koenvanwijk commented
A colleague of mine is working on this one now.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Beka Westberg ***@***.***>
Sent: Friday, January 5, 2024 5:32:04 PM
To: google/blockly-samples ***@***.***>
Cc: Koen van Wijk ***@***.***>; Mention ***@***.***>
Subject: Re: [google/blockly-samples] Add indexing of dropdown entries (PR #2004)


Heya @koenvanwijk<https://github.com/koenvanwijk> are you still interested in working on this? I'll check back in a week and close it if not!

—
Reply to this email directly, view it on GitHub<https://github.com/google/blockly-samples/pull/2004#issuecomment-1878947210>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AB6YZCJAPWUIXGWOSRHDY73YNATIJAVCNFSM6AAAAAA5SSH6G6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZYHE2DOMRRGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



-------- Disclaimer --------
This email and any files transmitted may contain proprietary and confidential information of ICT Group or any of its subsidiaries (“ICT”) and is intended only for the (use of the) named recipient(s) above. If you have received this message in error or are not the intended or named recipient(s) of this message, please immediately notify the sender by return and delete this email message from your computer. Any views or opinions presented are solely those of its author and do not necessarily represent those of ICT. You are hereby notified that unauthorized disclosure, use, dissemination, forwarding, printing or copying of this e-mail and its attachments either whole or partial of its contents is strictly prohibited. ICT cannot guarantee that email communications are secured and error-free and does not accept any liability for damages resulting from the use of email. The general terms and conditions of purchase respectively sale and delivery of ICT are applicable to all transactions and undertakings resulting therefrom.

2024-01-12 16:24 UTC, BeksOmega commented
I'm going to go ahead and close this PR =) Looking forward to reviewing a new one with the change!

2024-01-12 16:24 UTC, closed without merging