feature: Enable strict mode for workspace search #2032
RaspberryPiFoundation/blockly-samples pull request #2079
Opened 2023-11-19 17:27 UTC by sdthaker

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details
### Resolves

Fixes #2032 

### Proposed Changes

* Enabled strict mode for TS code.

* Fixed TS errors include _(a lot of the errors were repetitive for different pieces of code_)_:
   ```Javascript
   TS2345: Argument of type '(evt: KeyboardEvent) => void' is not assignable to parameter of type '(event: Event) => void'.
     Types of parameters 'evt' and 'event' are incompatible.
       Type 'Event' is missing the following properties from type 'KeyboardEvent': altKey, charCode, code, ctrlKey, and 17 
   more.
   ```
   ```Javascript
   TS2531: Object is possibly 'null'.
   ```
   ```Javascript
   TS2345: Argument of type '(e: KeyboardEvent) => void' is not assignable to parameter of type '(event: Event) => void'.
  Types of parameters 'e' and 'event' are incompatible.
    Type 'Event' is not assignable to type 'KeyboardEvent'.
   ```
   ```Javascript
    TS7034: Variable 'topBlockText' implicitly has type 'any[]' in some locations where its type cannot be determined.
   ```
   ```Javascript
   TS7005: Variable 'topBlockText' implicitly has an 'any[]' type.
   ```

### Reason for Changes

To enhance compile-time type checking built-in with TS to avoid potential errors during runtime.

* `npm run lint` results: 
   >![image](https://github.com/google/blockly-samples/assets/71615163/3bf6607e-405f-4ca3-b967-695881a6c0b0)
* `npm run build` results:
   >![image](https://github.com/google/blockly-samples/assets/71615163/59f3af1a-41b7-4e53-a004-ed9781234b69)
* `npm run test` results:
   >![image](https://github.com/google/blockly-samples/assets/71615163/b52cdeff-6e05-4f3d-a8e9-4d967bfb09a0)

### Test Coverage

N/A

### Documentation

N/A

### Additional Information

2023-11-20 18:49 UTC, BeksOmega requested changes
This looks great :D Just a few nits / preferences then LGTM!

2023-11-20 18:49 UTC, BeksOmega commented on plugins/workspace-search/src/workspace_search.ts
> +      }
I think you can use an optional chaining operator here.
```suggestion
      this.inputElement?.select();
```

2023-11-20 18:49 UTC, BeksOmega commented on plugins/workspace-search/src/workspace_search.ts
> +    func: (event: T) => void,
Woot this looks great!

2023-11-20 18:49 UTC, BeksOmega commented on plugins/workspace-search/src/workspace_search.ts
> +    }
```suggestion
    this.actionDiv?.appendChild(btn);
```

2023-11-20 18:49 UTC, BeksOmega commented on plugins/workspace-search/src/workspace_search.ts
> +      }
Can you cahnge this to `if (this.searchOnInput && this.inputElement)`? Not sure if that works but I think it'd be more readable.

2023-11-20 18:49 UTC, BeksOmega commented on plugins/workspace-search/src/workspace_search.ts
> +    }
```suggestion
    this.inputElement?.focus();
```

2023-11-20 19:35 UTC, sdthaker commented
@BeksOmega Thanks for the review! I've pushed the commit! Just wanted to know the reason for using optional chaining for certain pieces of code and not for the others.

2023-11-20 21:23 UTC, sdthaker commented
> @BeksOmega Thanks for the review! I've pushed the commit! Just wanted to know the reason for using optional chaining for certain pieces of code and not for the others.

I'm assuming it was a choice about better code readability?

2023-11-21 16:59 UTC, BeksOmega commented
> @BeksOmega Thanks for the review! I've pushed the commit! Just wanted to know the reason for using optional chaining for certain pieces of code and not for the others.

So in certain places like assignments, optional chaining is not allowed. For example:

```js
this.myPossiblyNullObj?.property = 'my new value';
```

Because optional chaining makes the expression evaluate to `undefined` if the thing being accessed is null or undefined. So in this case what you're doing is basically:

```js
undefined = 'my new value';
```

Which is not allowed.

And in other cases it is just a style thing like you said :P In general I prefer optional chaining for one-line things. But if you're going to access the object multiple times, I usually prefer to early return.

If you have any questions or preferences about specific cases lmk!

2023-11-21 17:10 UTC, BeksOmega approved these changes

2023-11-21 17:15 UTC, sdthaker commented
> > @BeksOmega Thanks for the review! I've pushed the commit! Just wanted to know the reason for using optional chaining for certain pieces of code and not for the others.
> 
> So in certain places like assignments, optional chaining is not allowed. For example:
> 
> ```js
> this.myPossiblyNullObj?.property = 'my new value';
> ```
> 
> Because optional chaining makes the expression evaluate to `undefined` if the thing being accessed is null or undefined. So in this case what you're doing is basically:
> 
> ```js
> undefined = 'my new value';
> ```
> 
> Which is not allowed.
> 
> And in other cases it is just a style thing like you said :P In general I prefer optional chaining for one-line things. But if you're going to access the object multiple times, I usually prefer to early return.
> 
> If you have any questions or preferences about specific cases lmk!

This is great information! Thanks so much! Just wanted to know for my reference to get a better insight on the optional chaining case. :)

2023-11-21 19:35 UTC, merged