feature: enabled TS strict mode, resolved TS errors
RaspberryPiFoundation/blockly-samples pull request #2080
Opened 2023-11-19 18:43 UTC by sdthaker

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details
### Resolves

Fixes #2030 

### Proposed Changes

* Enabled strict mode for TS code.

* Fixed TS errors include _(a lot of the errors were repetitive for different pieces of code)_:
   ```Javascript
   TS2345: Argument of type 'BackpackContextMenuOptions | undefined' is not assignable to parameter of type 'BackpackContextMenuOptions'.
  Type 'undefined' is not assignable to type 'BackpackContextMenuOptions'.
   ```
   ```Javascript
   TS2322: Type '{ [rendererConstant: string]: any; } | null' is not assignable to type '{ [rendererConstant: string]: any; } | undefined'.
  Type 'null' is not assignable to type '{ [rendererConstant: string]: any; } | undefined'.
   ```
   ```Javascript
   TS18047: 'HorizontalFlyout' is possibly 'null'.
   ```
   ```Javascript
   TS18047: 'VerticalFlyout' is possibly 'null'.
   ```
   ```Javascript
   TS18047: 'parentNode' is possibly 'null'.
   ```
   ```Javascript
   TS2345: Argument of type 'SVGElement | null' is not assignable to parameter of type 'Element'.
  Type 'null' is not assignable to type 'Element'.
   ```
   ```Javascript
    TS2531: Object is possibly 'null'.
   ```
   ```Javascript
   TS7006: Parameter 'json' implicitly has an 'any' type.
   ```
   ```Javascript
   TS7006: Parameter 'keys' implicitly has an 'any' type.
   ```
   ```Javascript
   TS2322: Type '(menuOptions: ContextMenuOption[], e: PointerEvent) => void' is not assignable to type '(menuOptions: ContextMenuOption[], e: Event) => void'.
  Types of parameters 'e' and 'e' are incompatible.
    Type 'Event' is missing the following properties from type 'PointerEvent': height, isPrimary, pointerId, pointerType, and 33 more.
   ```
   ```Javascript
   TS18048: 'scope.block' is possibly 'undefined'.
   ```
   ```Javascript
   TS18047: 'scope.block.workspace.targetWorkspace' is possibly 'null'.
   ```
   ```Javascript
   TS2345: Argument of type 'BlockSvg | undefined' is not assignable to parameter of type 'Block'.
  Type 'undefined' is not assignable to type 'Block'.
   ```
   ```Javascript
   TS2345: Argument of type '{ displayText: (scope: Scope) => string | undefined; preconditionFn: (scope: Scope) => "enabled" | "hidden" | "disabled"; callback: (scope: Scope) => void; scopeType: ScopeType; id: string; weight: number; }' is not assignable to parameter of type 'RegistryItem'.
  Types of property 'displayText' are incompatible.
    Type '(scope: Scope) => string | undefined' is not assignable to type 'string | ((p1: Scope) => string)'.
      Type '(scope: Scope) => string | undefined' is not assignable to type '(p1: Scope) => string'.
        Type 'string | undefined' is not assignable to type 'string'.
          Type 'undefined' is not assignable to type 'string'.
   ```
   ```Javascript
    TS18048: 'ws' is possibly 'undefined'.
   ```
   ```Javascript
   TS2345: Argument of type 'WorkspaceSvg | undefined' is not assignable to parameter of type 'Workspace'.
  Type 'undefined' is not assignable to type 'Workspace'.
   ```
   ```Javascript
   TS2345: Argument of type 'boolean | undefined' is not assignable to parameter of type 'boolean'.
  Type 'undefined' is not assignable to type 'boolean'.
   ```
   ```
   TS7053: Element implicitly has an 'any' type because expression of type '"isOpen"' can't be used to index type 'AbstractEventJson'.
  Property 'isOpen' does not exist on type 'AbstractEventJson'.
   ```

### Reason for Changes

To enhance compile-time type checking built-in with TS to avoid potential errors during runtime.

* `npm run lint` results: 
   >![image](https://github.com/google/blockly-samples/assets/71615163/fc815ce0-01c2-4105-859f-088752a8f920)
* `npm run build` results:
   >![image](https://github.com/google/blockly-samples/assets/71615163/5c9980d3-3409-4bbd-b616-030172a84a85)
* `npm run test` results:
   No tests found for workspace-backpack plugin

### Test Coverage

N/A

### Documentation

N/A

### Additional Information

2023-11-20 00:02 UTC, sdthaker commented
I received build time error 
```Typescript
TS2550: Property 'includes' does not exist on type 'string[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2016' or later.'.
```
hence made [this commit](https://github.com/google/blockly-samples/pull/2080/commits/98324f4d6e16dc701cc667503556484643a7fe15). Please let me know if there's a better way to fix this error.

2023-11-20 19:04 UTC, BeksOmega requested changes
Changes look great! Just a few nits =)

2023-11-20 19:04 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.ts
> +      if (HorizontalFlyout) {
I think in this case we actually want to error, because we're trying to create a horizontal layout but no horizontal flyout exists. Same for the vertical case below.

2023-11-20 19:04 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.ts
>      this.flyout_.init(this.workspace_);
I think you can change this to optional dereference.

2023-11-20 19:04 UTC, BeksOmega commented on plugins/workspace-backpack/test/index.ts
> +  const rootElement = document.getElementById('root');
This looks good!

2023-11-20 19:04 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.ts
> +    const traverseJson = function (json: StateWithIndex, keys: string[]) {
Does this work if you just use the `Blockly.serialization.blocks.State` type?

2023-11-20 19:04 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.ts
> +    if (this.flyout_) this.flyout_.show(jsons);
Optional dereference here and below.

2023-11-20 19:04 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.ts
> +    if (e instanceof MouseEvent && Blockly.browserEvents.isRightButton(e)) {
Nice!

2023-11-20 19:04 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack_helpers.ts
> +      if (scope.block) {
Can you change this to `if (!scope.block) return 'hidden';` Here and below.

2023-11-20 19:54 UTC, sdthaker commented on plugins/workspace-backpack/src/backpack.ts
> +    const traverseJson = function (json: StateWithIndex, keys: string[]) {
Received these errors when using `Blockly.serialization.blocks.State`:

![image](https://github.com/google/blockly-samples/assets/71615163/997f357d-cf34-4efd-8df0-ba6949dbacf6)

Code changes: 

![image](https://github.com/google/blockly-samples/assets/71615163/469379d4-3e7a-4bd6-9bb9-9f8c92c8415a)

2023-11-20 20:11 UTC, sdthaker commented
Pushed all the changes except [this](https://github.com/google/blockly-samples/pull/2080#discussion_r1399621418). Please let me know how to proceed further with that review and if I missed anything for the other reviews. :)

2023-11-20 20:20 UTC, sdthaker commented on plugins/workspace-backpack/src/backpack.ts
> +    const traverseJson = function (json: StateWithIndex, keys: string[]) {
I'm assuming the compiler isn't able to infer the fact that the keys of `State` interface would be of type string, which the interface I created `StateWithIndex` resolves. I might be wrong here.

2023-11-21 17:18 UTC, BeksOmega commented on plugins/workspace-backpack/src/backpack.ts
> +    const traverseJson = function (json: StateWithIndex, keys: string[]) {
Ah ok in that case I think this fix makes sense!

2023-11-21 17:19 UTC, BeksOmega approved these changes

2023-11-21 17:22 UTC, sdthaker commented on plugins/workspace-backpack/src/backpack.ts
> +    const traverseJson = function (json: StateWithIndex, keys: string[]) {
Ok great! I'll push those changes soon! :)

2023-11-21 17:23 UTC, sdthaker commented on plugins/workspace-backpack/src/backpack.ts
> +    const traverseJson = function (json: StateWithIndex, keys: string[]) {
Whoops my bad, they're already part of this PR!

2023-11-21 19:36 UTC, merged