feat: Create Hacker mode theme #1988
RaspberryPiFoundation/blockly-samples pull request #2091
Opened 2023-12-04 12:38 UTC by shivalipatel6

I created a theme with a black background, black block fill for all blocks, a white shadow for all blocks (still working on putting in an actual outline), dark toolbox, dark flyout, and monospace text. I am still working on putting in green text for all block text. Need to fix CSS issue first.

## The basics

- [ X] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details
### Resolves

Fixes 

### Proposed Changes
This pull request creates a new blockly theme that has a black background for everything, black fill in for blocks and a white highlight. Theme is currently incomplete as it is missing green text color, but it will be fixed later once some CSS work is fixed. 
![hacker-modescreenshot1](https://github.com/google/blockly-samples/assets/56765670/56cc1e1e-6c89-4e82-aa26-ddf27c8a9eb2)

### Reason for Changes

### Test Coverage

### Documentation

 Once the theme is made public, the documentation about themes will need to be updated to let users know the theme exists. As well documentation about how to download the theme will be needed. 

### Additional Information

2023-12-05 17:33 UTC, BeksOmega requested changes
This is looking great so far! Thank you for putting the work into this and dealing with all of the crazy rebasing =)

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/package.json
> +{
Can you mark this package as [private](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#private)?

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/package.json
Sorry the create-package script doesn't work quite correctly for first party plugins, so this file needs some manual fixes. Will list below!

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/package.json
> +  "name": "blockly-theme-hackermode",
```suggestion
  "name": "@blockly/theme-hackermode",
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/package.json
> +  "description": "A Blockly theme.",
Can you update this to be more descriptive?

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/README.md
> +# blockly-theme-hackermode [![Built on Blockly](https://tinyurl.com/built-on-blockly)](https://github.com/google/blockly)
```suggestion
# @blockly/theme-hackermode [![Built on Blockly](https://tinyurl.com/built-on-blockly)](https://github.com/google/blockly)
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/README.md
> +import Theme from 'blockly-theme-hackermode';
```suggestion
import Theme from '@blockly/theme-hackermode';
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/README.md
> +A [Blockly](https://www.npmjs.com/package/blockly) theme that ...
Can you update this to be more descriptive?

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/README.md
> +yarn add blockly-theme-hackermode
```suggestion
yarn add @blockly/theme-hackermode
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/README.md
> +npm install blockly-theme-hackermode --save
```suggestion
npm install @blockly/theme-hackermode --save
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/GETSTARTED.md
Please delete this file.

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/package.json
> +  "publishConfig": {},
```suggestion
  "publishConfig": {
    "access": "public",
    "registry": "https://wombat-dressing-room.appspot.com"
  },
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/src/index.js
> + */
Please complete.

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/src/index.js
> +import Blockly from 'blockly/core';
```suggestion
import * as Blockly from 'blockly/core';
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/package.json
> +  "homepage": "git@github.com:shivalipatel6/blockly-samples/tree/master/plugins/theme-hackermode#readme",
```suggestion
  "homepage": "git@github.com:google/blockly-samples/tree/master/plugins/theme-hackermode#readme",
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/package.json
> +    "url": "git@github.com:shivalipatel6/blockly-samples/issues"
```suggestion
    "url": "git@github.com:google/blockly-samples/issues"
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/package.json
> +    "url": "git@github.com:shivalipatel6/blockly-samples.git",
```suggestion
    "url": "git@github.com:google/blockly-samples.git",
```

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/src/index.js
> +export default Blockly.Theme.defineTheme('THEME_NAME', {
Please complete.

2023-12-05 17:33 UTC, BeksOmega commented on plugins/theme-hackermode/src/index.js
This file looks great =)

2023-12-05 18:42 UTC, maribethb commented
Hi @shivalipatel6 you can also run the create-package script with the `--first-party` flag and it will use the correct values for many of the things Beka noted. Whether you want to re-run the script and then re-apply your changes, or just fix the issues Beka noted manually is up to you!

2023-12-06 20:09 UTC, shivalipatel6 commented on plugins/theme-hackermode/src/index.js
I tackled the issues you pointed out manually. Hopefully I did everything right. Thank you so much for helping me tackle this issue and for your patience with all the problems I kept stumbling into.

2023-12-07 17:29 UTC, BeksOmega requested changes
Thanks for the fixes! Just a few more nits then this should be good to go =)

2023-12-07 17:29 UTC, BeksOmega commented on plugins/theme-hackermode/src/index.js
> +private:true
This needs to be added to the `package.json` file as a config property!

E.g.:

```json
  "main": "./dist/index.js",
  "module": "./src/index.js",
  "unpkg": "./dist/index.js",
  // This added.
  "private": true,
  "author": "",
```

2023-12-07 17:29 UTC, BeksOmega commented on plugins/theme-hackermode/src/index.js
> +// TODO: Edit theme overview.
Can you remove this TODO now that it's completed?

2023-12-07 17:29 UTC, BeksOmega commented on plugins/theme-hackermode/src/index.js
> +// TODO: Edit theme name.
Can you remove this TODO?

2023-12-07 17:29 UTC, BeksOmega commented on plugins/theme-hackermode/README.md
> +  -->
Can you remove this TODO now that it's completed?

2023-12-08 15:55 UTC, BeksOmega commented
@shivalipatel6 Please resolve the build errors. You should be able to run `npm run build` to reproduce the problem. Let me know if you need help!

2023-12-08 20:49 UTC, shivalipatel6 commented
I fixed up the build issues, but I am still unsure what is up with the format issues... I could use some pointers for figuring this out.

2023-12-09 00:06 UTC, BeksOmega commented
> I fixed up the build issues, but I am still unsure what is up with the format issues... I could use some pointers for figuring this out.

Can you try running `npm ci` and then `npm run format` from the root level of the repository? That should create some changes you can commit to fix it!

2023-12-10 11:57 UTC, shivalipatel6 commented
> > I fixed up the build issues, but I am still unsure what is up with the format issues... I could use some pointers for figuring this out.
> 
> Can you try running `npm ci` and then `npm run format` from the root level of the repository? That should create some changes you can commit to fix it!

I was able to run both commands and produce changes, but it was unable to fix the format issues. Is there anything I can run that will help me diagonse these problems?

2023-12-11 22:59 UTC, BeksOmega commented
> > > I fixed up the build issues, but I am still unsure what is up with the format issues... I could use some pointers for figuring this out.
> > 
> > 
> > Can you try running `npm ci` and then `npm run format` from the root level of the repository? That should create some changes you can commit to fix it!
> 
> I was able to run both commands and produce changes, but it was unable to fix the format issues. Is there anything I can run that will help me diagonse these problems?

Hm you're right. I also pulled your branch and the format check passed.

Could you try rebasing onto the latest master and then rerunning the formatting commands? It could be that the quoting change you fixed in your other PR (thank you again!) is causing conflicts.

2023-12-12 23:11 UTC, shivalipatel6 commented
I ran npm ci and npm run format after I rebased and merged the changes from master into this branch but there was no changes to commit...

2023-12-14 00:57 UTC, BeksOmega commented
Hiya @shivalipatel6 Wanted to let you know I saw this but my team is doing a hackathon this week! So I'll get back to you about this in a few days. Sorry for the delay!

2023-12-14 03:35 UTC, shivalipatel6 commented
> Hiya @shivalipatel6 Wanted to let you know I saw this but my team is doing a hackathon this week! So I'll get back to you about this in a few days. Sorry for the delay!

Have fun at the hackathon!! Good luck with your projects!

2023-12-15 22:49 UTC, BeksOmega commented
I pushed a commit to your branch with the formatting fixes! Thanks for the work on this @shivalipatel6 =)

2023-12-15 22:50 UTC, merged