fix: add boolean to dispose function call (#2217)
RaspberryPiFoundation/blockly-samples pull request #2341
Opened 2024-05-06 22:21 UTC by sancodes

## The basics
- [X] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details
### Resolves
Fixes #2217

### Proposed Changes

- adds true to the dispose()
- ![Screenshot 2024-05-06 at 3 14 45 PM](https://github.com/google/blockly-samples/assets/52472550/d17cd604-2ab7-4fc4-9d66-f3848b1438d4)

### Reason for Changes
- adding `dispose(true)` makes sure the blocks that are not associated with the procedures block remain **undeleted**

- ### Test Coverage
![Screenshot 2024-05-06 at 3 17 33 PM](https://github.com/google/blockly-samples/assets/52472550/a02ea0a0-d70e-4bcb-b90a-9db46d40e7a6)

- Test, I tried to recreate, the blocks being connected to each other, and mimicking the deletion process of procedures child, which should still keep the other blocks intact and undeleted

2024-05-06 22:42 UTC, BeksOmega requested changes
Hello! Your testing logic is correct but your test code doesn't do what you want it to.

After that fix I'll pull it down to test manually. Then should be good to go =)

2024-05-06 22:42 UTC, BeksOmega commented on plugins/block-shareable-procedures/test/procedure_blocks.mocha.js
> +        callBlock1.nextConnection.outputConnection = ifBlock2;
```suggestion
        ifBlock1.nextConnection.connect(callBlock1.previousConnection);
        callBlock1.nextConnection.connect(ifBlock2.previousConnection);
```

2024-05-07 01:28 UTC, sancodes commented
@BeksOmega applied your suggestions.

2024-05-07 18:07 UTC, BeksOmega approved these changes
Tested locally and this LGTM =)

Thank you for the fix!!

2024-05-07 18:07 UTC, merged

2024-05-07 20:21 UTC, sancodes commented
@BeksOmega Thank you :)