Fix: Migrating every theme to TypeScript.
RaspberryPiFoundation/blockly-samples pull request #2474
Opened 2024-12-30 22:36 UTC by tgbhy

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

## The details
### Resolves

Fixes https://github.com/google/blockly-samples/issues/2158

### Proposed Changes

Migrate every theme sample to TypeScript.

### Reason for Changes

It would be usable in TypeScript like explained in the fixed issue.

### Test Coverage

Manually tested with a Windows 10 PC and Brave Browser.
I tested on using a default installation of Blockly and recreating the schema of each readme-media/Theme.png

2025-01-09 16:38 UTC, cpcallen approved these changes

2025-01-09 16:45 UTC, cpcallen commented
Hi @tgbhy.  Thanks for this useful PR!  The changes look good but there are some additional steps needed before we can accept the PR:

* You'll need to agree to the CLA.
* eslint is unhappy about all the properties with underscores in their name.  You'll need to disable this rule for these declarations.
* You'll also need to run `npm run format` to run Prettier and thereby fix the formatting.

2025-01-18 15:01 UTC, tgbhy commented
Working on it !

2025-01-24 19:19 UTC, cpcallen requested changes

2025-01-24 19:19 UTC, cpcallen commented on plugins/theme-deuteranopia/src/index.ts
> +  colourBlocks: {
So, renaming these properties will break the theme.  This is one case where you have _suppress_ the eslint errors, rather than changing the code so there isn't an error:

```suggestion
  colour_blocks: { // eslint-disable-line camelcase
```

(Here and many other places in this PR.)

2025-01-24 19:19 UTC, cpcallen commented on plugins/theme-deuteranopia/package.json
> +    "@blockly/theme-deuteranopia": "file:"
Not sure what you did while creating 3c49ad6 that caused this (and related changes to `package-lock.json`), but this change looks weird (a package should not in general depend upon itself!) and should probably be reverted.

(Here and in the other themes.)

2025-01-24 19:21 UTC, tgbhy commented on plugins/theme-deuteranopia/package.json
> +    "@blockly/theme-deuteranopia": "file:"
Ye, I think it's my VSCode that bugged, let me correct this one in a few minutes.
Sorry for this thing I didn't saw it =x

2025-01-24 19:34 UTC, tgbhy commented on plugins/theme-deuteranopia/src/index.ts
> +  colourBlocks: {
It doesn't seems to destroy the theme for me after my tests

2025-01-24 19:39 UTC, tgbhy commented on plugins/theme-deuteranopia/src/index.ts
> +  colourBlocks: {
So tell me if you want me to do it but the one or the other isn't breaking so...

2025-02-24 14:47 UTC, cpcallen requested changes

2025-02-24 14:47 UTC, cpcallen commented on plugins/theme-dark/package-lock.json
Please revert any changes to any `package-lock.json` file in this branch, since AFAICT there should be no changes to any `package.json` file to justify them.

(General dependency updates not resulting from a change to `package.json` should be done in a separate PR.)

2025-02-24 14:47 UTC, cpcallen commented on plugins/theme-dark/package.json
> +    "@blockly/theme-dark": "file:"
As discussed previously (in a different directory): please revert.

2025-02-24 14:47 UTC, cpcallen commented on plugins/theme-deuteranopia/package-lock.json
Please revert.

2025-02-24 14:47 UTC, cpcallen commented on plugins/theme-deuteranopia/src/index.ts
> +  colourBlocks: {
Please revert the property name changes.  The theme won't work if your rename them.

2025-02-24 14:47 UTC, cpcallen commented on plugins/theme-hackermode/package-lock.json
Please revert.

2025-02-24 14:47 UTC, cpcallen commented on plugins/theme-highcontrast/package-lock.json
Please revert.

2025-02-24 14:47 UTC, cpcallen commented on plugins/theme-modern/package-lock.json
Please revert.

2025-02-24 14:47 UTC, cpcallen commented on plugins/theme-tritanopia/package-lock.json
Please revert.

2025-02-24 15:33 UTC, tgbhy commented
This is fine now ?

2025-03-10 16:44 UTC, cpcallen requested changes

2025-03-10 16:44 UTC, cpcallen commented on plugins/theme-deuteranopia/src/index.ts
> +  colourBlocks: {
Please apply the suggested change above, and equivalent changes to each of the other names below.

2025-03-10 19:08 UTC, tgbhy commented
Wait, it's already the case ?
Where did you see that, it's already the case of being "colourBlocks" in every themes...

2025-05-05 06:29 UTC, tgbhy commented
Bump here

2025-05-09 18:34 UTC, maribethb commented
Hi @tgbhy we can't merge this because renaming the properties will break them. I'm not sure how you tested the change, but the way themes work are that they correlate a category name to a set of styles. The category names like `colour_blocks` are set in core, so changing them here and not in core would break the theme as there is no category name called `colourBlocks`. And we are not interested in changing the category names in core.

We can accept this PR after you address Christopher's comment here https://github.com/google/blockly-samples/pull/2474/files#r1929130761

Please let us know if you have further questions. Thanks for your work on this and for following up!

2025-05-09 18:36 UTC, tgbhy commented
oh okay, I don't know why it was working perfectly for me...
I'll do the change, you can come back in less than an hour I think ;)

2025-05-09 19:10 UTC, maribethb commented
You will need to fix this for all of the `defaultBlockStyles` and `categoryStyles`, not just the `colour_blocks`.

2025-05-11 09:19 UTC, tgbhy commented
So wait, I need to do this only for `defaultBlockStyle` (-> `default_block_style`) and `categoryStyles` (-> `category_style`) ?
After that it's finish ?

Because I really don't understand why you ask me that because it was working fine for me but whatever, just confirm me that and I'll do the changes.

2025-05-12 16:23 UTC, maribethb commented
You can check how a theme is supposed to look on the published plugin showcase page. Here's what the highcontrast theme is supposed to look like, for example: https://google.github.io/blockly-samples/plugins/theme-highcontrast/test/index.html

You can test your change by running `npm start` from the plugin's directory. When I checkout your PR and run `npm start` from the highcontrast plugin, here's what I see:

![Screenshot 2025-05-12 at 9 17 32 AM](https://github.com/user-attachments/assets/85c210b4-25fd-4a37-9358-c31ed606771a)

All of the blocks are black and the toolbox is missing the little color stripe for the category. This means your theme is broken.

You can read more about how themes work [here](https://developers.google.com/blockly/guides/configure/web/appearance/themes).

The properties in the theme like `defaultBlockStyle` and `categoryStyle` are supposed to be camel case. However, those properties are objects where the keys are arbitrary values set by the owner of the blocks. If an application owner creates their own block category and decides to call it `mY_SpEcIaL_BlOcKs`, that's what would have to go in as the object key, so that blockly can match that name from the toolbox definition to the theme definition. The themes you're editing provide values for the default blocks and categories that Blockly ships with (like `logic_blocks`, `math_blocks`, and so on). Since Blockly uses snake case for these values, the theme has to as well.

This PR shouldn't change any object keys as part of the change. You should revert all of those kinds of changes. If the key was previously `logic_blocks` it needs to remain that way. If the key was previously `defaultBlockStyles` it needs to remain that way. Does that help?

2025-05-12 17:04 UTC, tgbhy commented
Okay thank you, I will do all the edits right now.

2025-05-12 17:37 UTC, tgbhy commented
And done !

2025-05-14 17:56 UTC, maribethb commented on plugins/theme-dark/package.json
> +    "@blockly/theme-dark": "file:"
This change needs to be removed from this PR.

2025-05-14 18:10 UTC, tgbhy commented
Give me a sec I have an idea
I'm really sorry for this ^^'

2025-05-14 18:17 UTC, tgbhy commented
And the work is done !
Sorry, I'l pay attention to that the next time ^^

2025-05-14 18:25 UTC, tgbhy commented on plugins/theme-dark/package.json
> +    "@blockly/theme-dark": "file:"
All changes has been made for this.

2025-05-19 16:24 UTC, tgbhy commented
Any news here ?

2025-05-21 15:08 UTC, cpcallen approved these changes
Thanks for the changes; they look great—and sorry for the delayed review: we were busy with the Blockly  v12 release.

2025-05-21 15:52 UTC, tgbhy commented
No problem. Will it be merged now, or does it need more modifications?

2025-05-21 15:54 UTC, merged