Using the testHelper from #637 inside of navigation_modify_test
RaspberryPiFoundation/blockly-samples pull request #648
Opened 2021-04-02 17:09 UTC by ricknjacky

issue ref:- #567

2021-04-02 17:11 UTC, ricknjacky commented
![image](https://user-images.githubusercontent.com/50985033/113437518-63330480-9404-11eb-8ce0-3326c123daee.png)

@moniika as you can clearly see, there are some ESLinting problems I presume.. Any heads up on how to obviate them?
Also, any suggestions on this PR?

2021-04-05 19:35 UTC, moniika reviewed
> ![image](https://user-images.githubusercontent.com/50985033/113437518-63330480-9404-11eb-8ce0-3326c123daee.png)
> 
> @moniika as you can clearly see, there are some ESLinting problems I presume.. Any heads up on how to obviate them?
> Also, any suggestions on this PR?

Just follow the github action comments (you can see them on the [files changed tab](https://github.com/google/blockly-samples/pull/648/files)). This PR otherwise looks good to me.

2021-04-05 19:35 UTC, moniika commented on plugins/keyboard-navigation/test/navigation_modify_test.mocha.js
The eslint check ("Block must not be padded by blank lines") is complaining about this extra line here.

2021-04-05 19:35 UTC, moniika requested changes
Just fix the eslint issues and it looks good.

2021-04-06 17:32 UTC, moniika approved these changes
Thanks for the PR!

2021-04-06 17:49 UTC, merged